api_platform:
    graphql:
        enabled: true
    title: Actors/Movies App
    version: 1.0.0
    # remove spider
    show_webby: false
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_items_per_page: 5
        pagination_client_items_per_page: true
    #    graphql:
    #        collection:
    #            pagination:
    #                enabled: true
    collection:
        pagination:
            items_per_page_parameter_name: 'daisy'


