<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD2xZlfj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD2xZlfj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD2xZlfj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD2xZlfj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD2xZlfj\App_KernelDevDebugContainer([
    'container.build_hash' => 'D2xZlfj',
    'container.build_id' => '3cef14c5',
    'container.build_time' => 1697701738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD2xZlfj');
