<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0vsGOqk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0vsGOqk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0vsGOqk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0vsGOqk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0vsGOqk\App_KernelDevDebugContainer([
    'container.build_hash' => '0vsGOqk',
    'container.build_id' => '4bfc9e5d',
    'container.build_time' => 1696854815,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0vsGOqk');
