<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQg8Yl0x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQg8Yl0x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQg8Yl0x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQg8Yl0x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQg8Yl0x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qg8Yl0x',
    'container.build_id' => '05933de4',
    'container.build_time' => 1701944858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQg8Yl0x');
